package com.wanli.collect.dao.mapper;

import com.wanli.collect.model.entity.Board;

public interface BoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insert(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int insertSelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    Board selectByPrimaryKey(String boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Board record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table board
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Board record);
}