package com.wanli.collect.dao.mapper;

import com.wanli.collect.model.entity.CollectData;

public interface CollectDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    int insert(CollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    int insertSelective(CollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    CollectData selectByPrimaryKey(Long dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CollectData record);
}