package com.wanli.collect.dao.mapper;

import com.wanli.collect.model.entity.Transducer;

public interface TransducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    int insert(Transducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    int insertSelective(Transducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    Transducer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Transducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Transducer record);
}