package com.wanli.collect.dao.mapper;

import com.wanli.collect.model.entity.TransducerDataConf;

public interface TransducerDataConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    int insert(TransducerDataConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    int insertSelective(TransducerDataConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    TransducerDataConf selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransducerDataConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transducer_data_conf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransducerDataConf record);
}