package com.wanli.collect.model.entity;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Application {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_id
     *
     * @mbg.generated
     */
    private Long applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_name
     *
     * @mbg.generated
     */
    private String applicationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_company
     *
     * @mbg.generated
     */
    private String applicationCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_flag
     *
     * @mbg.generated
     */
    private String applicationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_time
     *
     * @mbg.generated
     */
    private Instant applicationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.application_description
     *
     * @mbg.generated
     */
    private String applicationDescription;
}