package com.wanli.collect.model.entity;

import com.wanli.collect.model.constants.BoardStatusType;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Board {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.board_id
     *
     * @mbg.generated
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.application_flag
     *
     * @mbg.generated
     */
    private String applicationFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.board_name
     *
     * @mbg.generated
     */
    private String boardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.board_status
     *
     * @mbg.generated
     */
    private BoardStatusType boardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.board_time
     *
     * @mbg.generated
     */
    private Instant boardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column board.board_description
     *
     * @mbg.generated
     */
    private String boardDescription;
}