package com.wanli.collect.model.entity;

import java.math.BigDecimal;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CollectData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.data_id
     *
     * @mbg.generated
     */
    private Long dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.board_id
     *
     * @mbg.generated
     */
    private String boardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.transducer_type
     *
     * @mbg.generated
     */
    private String transducerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.transducer_id
     *
     * @mbg.generated
     */
    private String transducerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.transducer_data
     *
     * @mbg.generated
     */
    private BigDecimal transducerData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_data.data_time
     *
     * @mbg.generated
     */
    private Instant dataTime;
}