package com.wanli.collect.model.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransducerType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transducer_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transducer_type.transducer_type
     *
     * @mbg.generated
     */
    private String transducerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transducer_type.transducer_unit
     *
     * @mbg.generated
     */
    private String transducerUnit;
}