package com.wanli.collect.model.entity;

import com.wanli.collect.model.constants.UserStatusType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.father_id
     *
     * @mbg.generated
     */
    private Long fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_username
     *
     * @mbg.generated
     */
    private String userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_status
     *
     * @mbg.generated
     */
    private UserStatusType userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.application_flag
     *
     * @mbg.generated
     */
    private String applicationFlag;
}